### PR TITLE
[feat] Implement the constructor

### PR DESCRIPTION
**Pull request by prashansatanwar**
This PR implements the constructor for Registry w.r.t. issue #20. I've added OpenZeppelin for access control.

### CODE REVIEW

**Comment by Akashneelesh** [comment]
Hey @prashansatanwar , could you do scarb fmt and then commit the code again.

**Comment by prashansatanwar** [comment]
done

**Comment by Akashneelesh** [comment]
Congratulations your PR has been merged @prashansatanwar !

**Comment by Akashneelesh** [comment]
The reward has been sent out, LFG ! @prashansatanwar

**Pull request merged**
