### PR TITLE
Implement the functionality of UpdateProfilePendingOwner

### LINKED ISSUE #9: [feat] Implement the functionality of UpdateProfilePendingOwner
Down below is the function that is to be implemented in the contract but in cairo.
https://github.com/allo-protocol/allo-v2/blob/4dd0ea34a504a16ac90e80f49a5570b8be9b30e9/contracts/core/Registry.sol#L253

Resources :
https://book.cairo-lang.org/
https://book.cairo-lang.org/ch14-03-contract-events.html?highlight=event#contract-events

If you have any doubts over on how to implement something similar to this you can try discovering few cairo code bases such as :

Unruggable memecoin : https://github.com/keep-starknet-strange/unruggable.meme/tree/main/packages/contracts/src
Blobstream : https://github.com/keep-starknet-strange/blobstream-starknet/tree/main/src

### PR DESCRIPTION
**Pull request by VictoriaAde**
This PR implements the `update_profile_pending_owner` function.
The function updates the "pending owner" of a specific profile. The "pending owner" is someone who is set to become the new owner of the profile.

Fixes #9

### CODE REVIEW

**Comment by VictoriaAde** [comment]
@Akashneelesh I am done with the task, please take a look.

**Comment by Akashneelesh** [comment]
Hey @VictoriaAde , could you please resolve the merge conflicts.

**Comment by VictoriaAde** [comment]
> Hey @VictoriaAde , could you please resolve the merge conflicts.

On it! I'm currently encountering crazy bugs, and fixing them atm.

**Comment by VictoriaAde** [comment]
Hi @Akashneelesh, I have fixed the conflicts and used the `_is_owner_of_profile` in my function to check for ownership.

**Comment by mikoU77** [comment]
good

**Comment by Akashneelesh** [comment]
@VictoriaAde The reward has been sent out. LFG

**Pull request merged**
